version: "3"
services:
  java-practice:
    image: gradle:jdk15
    container_name: java-practice
    volumes:
      - .:/code
    working_dir: /code
    tty: true
    stdin_open: true
    # override since we want to execute more gradle tasks
    entrypoint: tail
    command: -f /dev/null
